### ISSUE TITLE
Special character bash alias

### ISSUE THREAD

**Issue by elchior** [redbeard28/ansible-role-bashaliases#1]
I use a bash alias like
alias ...="cd ../.."

To make the role work for such aliases I had to change the regular expresion like this:
 ````
- name: "{{ ansible_distribution | lower }} | {{ ansible_distribution_release }} - Add aliases to {{ shell_aliases_file }}"
    lineinfile:
      dest: "{{ shell_aliases_file }}"
      create: true
      mode: 0644
      line: 'alias {{ item.alias }}="{{ item.command }}"'
      regexp: "^alias {{ 'item.alias' }}="
    with_items: "{{ shell_aliases }}"
```
